name: Build Linux AppImage

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install system deps
        run: sudo apt-get install -y python3-tk

      - name: Install AppImage Builder
        run: |
          sudo apt-get update
          sudo apt-get install -y libfuse2 python3-tk
          wget https://github.com/AppImageCrafters/appimage-builder/releases/download/v1.1.0/appimage-builder-1.1.0-x86_64.AppImage -O appimage-builder.AppImage
          chmod +x appimage-builder.AppImage
          sudo mv appimage-builder.AppImage /usr/local/bin/appimage-builder

      - name: Install pip deps
        run: pip install pyinstaller

      - name: Build binary
        run: pyinstaller --noconfirm --onefile --windowed eeprom.decoder.j518.py

      - name: Prepare AppDir
        run: |
          mkdir -p AppDir/usr/bin
          cp dist/eeprom.decoder.j518 AppDir/usr/bin/eeprom.decoder

      - name: Add desktop entry
        run: |
          mkdir -p AppDir/usr/share/applications
          cat > AppDir/audi.decoder.desktop <<EOF
          [Desktop Entry]
          Type=Application
          Name=EZSDecoder
          Exec=eeprom.decoder
          Icon=application-vnd.appimage
          Terminal=false
          Categories=Utility;
          EOF
          cp AppDir/audi.decoder.desktop AppDir/usr/share/applications/audi.decoder.desktop

      - name: Build AppImage
        run: |
          echo '
          version: 1
          AppDir:
            path: ./AppDir
            app_info:
              id: audi.decoder
              name: EZSDecoder
              exec: usr/bin/eeprom.decoder
              version: "1.1"
          ' > recipe.yml
          appimage-builder --recipe recipe.yml

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: EZSDecoder*.AppImage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
