name: Build Linux AppImage

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install python-appimage tool
        run: pip install python-appimage

      - name: Download Python runtime AppImage
        run: |
          wget https://github.com/niess/python-appimage/releases/download/python3.11/python3.11.8-cp311-cp311-manylinux2014_x86_64.AppImage
          chmod +x python3.11.8-cp311-cp311-manylinux2014_x86_64.AppImage

      - name: Prepare AppImage recipe
        run: |
          mkdir -p appimage-recipe
          echo "tkinter" > appimage-recipe/requirements.txt
          cp eeprom.decoder.j518.py appimage-recipe/
          cp audi.decoder.desktop appimage-recipe/
          echo '#!/bin/sh' > appimage-recipe/entrypoint.sh
          echo 'exec "${APPDIR}/python/bin/python3" eeprom.decoder.j518.py "$@"' >> appimage-recipe/entrypoint.sh
          chmod +x appimage-recipe/entrypoint.sh
          wget -O appimage-recipe/application-vnd.appimage.svg https://upload.wikimedia.org/wikipedia/commons/3/38/OOjs_UI_icon_package.svg

      - name: Build AppImage
        run: |
          python-appimage build app \
            -p ./python3.11.8-cp311-cp311-manylinux2014_x86_64.AppImage \
            appimage-recipe

      - name: List files
        run: ls -lh

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: '*.AppImage'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

